<script lang="ts">
    import Button from "$components/Button/Button.svelte"
    import { backIn, elasticIn } from "svelte/easing"

    // TODO I have not gotten viteimagetools imports to work for storybook to work yet
    // import Picture from "$components/Picture.svelte"
    // import noteTextureSrcSet from "$assets/images/note-texture.png?w=250;300&webp&srcset"
    // import { src, width, height } from "$lib/assets/images/note-texture.png?width=300&metadata"
    import noteTexture from "$assets/images/note-texture.png"
    import tapeTexture from "$assets/images/tape-texture-1.png"

    const RANDOM_SEED = Math.random()
    const TAPE_ROTATION_AMOUNT = RANDOM_SEED > 0.5 ? RANDOM_SEED * -4.2 : RANDOM_SEED * 4.2

    export let flyToRight = true

    let active = true

    function flyAway(_: HTMLElement, { duration, flyToRight }: { duration: number; flyToRight: boolean }) {
        const targetXSeed = RANDOM_SEED * 50

        return {
            duration,
            css: (t: number) => {
                const easedTimeStepIn = backIn(t)
                const y = (1 - t) * 110
                const x = (1 - elasticIn(t)) * targetXSeed
                return `
					transform:  rotate(${easedTimeStepIn * 1080}deg);
                    translate: ${flyToRight ? "" : "-"}${x}vw ${y}vh;
                    `
            }
        }
    }
</script>

{#if active}
    <div
        class="sticky-note absolute flex-column-center"
        style={`--rotation-amount: ${TAPE_ROTATION_AMOUNT}deg`}
        transition:flyAway={{ duration: 5000, flyToRight }}>
        <!-- TODO I have not gotten viteimagetools imports to work for storybook to work yet
             <Picture
            sources={{ srcset: noteTextureSrcSet, type: "webp" }}
            meta={{ src, width, height, alt: "sticky note texture generated by Dalle-2" }} /> -->
        <picture>
            <img src={noteTexture} alt="sticky note texture generated by Dalle-2" />
        </picture>
        <picture>
            <img src={tapeTexture} alt="tape texture generated by Dalle-2" />
        </picture>
        <slot />
        {#if active}
            <Button
                glow={false}
                hoverOverlay={false}
                label="remove note"
                on:click={(event) => {
                    active = false
                    const currentTarget = event.currentTarget
                    // TODO: Solve below @ts-ignore
                    // @ts-ignore
                    currentTarget.blur()
                    // @ts-ignore
                    currentTarget.style.opacity = "0"
                }} />
        {/if}
    </div>
{/if}

<style>
    .sticky-note {
        aspect-ratio: 1/1;
        padding: 1em;
        place-content: center;
        inset: 0;
    }
    :global(.sticky-note picture:nth-of-type(1)) {
        inset: 0;
    }
    :global(.sticky-note picture:nth-of-type(2)) {
        top: 0;
        translate: 0 -50%;
    }
    :global(.sticky-note picture:nth-of-type(2) img) {
        height: 25px;
        rotate: var(--rotation-amount);
    }
    :global(.sticky-note picture) {
        position: absolute;
        z-index: -1;
    }
    :global(.sticky-note button),
    :global(.sticky-note img) {
        height: 100%;
        border-radius: 3px;
    }
    :global(.sticky-note p),
    :global(.sticky-note button) {
        color: var(--black);
    }
    :global(.sticky-note button),
    :global(.sticky-note p) {
        font-family: var(--font-family-accent) !important;
    }
    :global(.sticky-note button) {
        --background-blur-amount: 20px;
        border: none !important;
        height: 100%;
        opacity: 0;
        position: absolute !important;
        text-decoration: underline;
        transition: opacity 420ms ease-in-out;
        width: 100%;
    }
    :global(.sticky-note:hover button),
    :global(.sticky-note button:focus) {
        opacity: 1;
    }
</style>
