<script lang="ts">
    // TODO I have not gotten viteimagetools imports to work for storybook to work yet
    // import Picture from "$components/Picture.svelte"
    // import noteTextureSrcSet from "$assets/images/note-texture.png?w=250;300&webp&srcset"
    // import { src, width, height } from "$lib/assets/images/note-texture.png?width=300&metadata"
    import noteTexture from "$assets/images/note-texture.png"
    import tapeTexture from "$assets/images/tape-texture-1.png"

    import HiddenInputs from "$components/HiddenInputs.svelte"
    import StickyNoteButton from "./StickyNoteButton.svelte"

    import { backIn, elasticIn } from "svelte/easing"
    import { enhance } from "$app/forms"

    import {
        type ScavengerHuntStates,
        scavengerHuntState,
        scavengerHuntStateKey,
    } from "$stores/states/scavengerHuntState"
    import { cookiesAllowed } from "$stores/settings/cookiesAllowed"
    import { setJSCookie } from "$utilities/setJSCookie"

    const RANDOM_SEED = Math.random()
    const TAPE_ROTATION_AMOUNT = RANDOM_SEED > 0.5 ? RANDOM_SEED * -4.2 : RANDOM_SEED * 4.2

    export let newScavengerHuntState: ScavengerHuntStates

    export let active: boolean = true
    export let flyToRight: boolean = true
    export let testid: string | undefined = undefined

    function flyAway(_: HTMLElement, { duration, flyToRight }: { duration: number; flyToRight: boolean }) {
        const targetXSeed = RANDOM_SEED * 50
        return {
            duration,
            css: (t: number) => {
                const easedTimeStepIn = backIn(t)
                const y = (1 - t) * 110
                const x = (1 - elasticIn(t)) * targetXSeed
                return `
					transform:  rotate(${easedTimeStepIn * 1080}deg);
                    translate: ${flyToRight ? "" : "-"}${x}vw ${y}vh;
                    `
            },
        }
    }
</script>

{#if active}
    <div
        class="sticky-note absolute flex-column-center"
        data-testid={testid}
        style={`--rotation-amount: ${TAPE_ROTATION_AMOUNT}deg`}
        transition:flyAway={{ duration: 5000, flyToRight }}>
        <!-- TODO I have not gotten viteimagetools imports to work for storybook to work yet
        <Picture
            sources={{ srcset: noteTextureSrcSet, type: "webp" }}
            meta={{ src, width, height, alt: "sticky note texture generated by Dalle-2" }} /> -->
        <picture>
            <img src={noteTexture} alt="sticky note texture generated by Dalle-2" />
        </picture>
        <picture>
            <img src={tapeTexture} alt="tape texture generated by Dalle-2" />
        </picture>
        <slot />
        {#if active}
            {#if $cookiesAllowed}
                <form
                    action="?/updateScavengerHuntState"
                    method="POST"
                    use:enhance={({ cancel }) => {
                        cancel()
                        $scavengerHuntState = newScavengerHuntState
                        if ($cookiesAllowed) setJSCookie(scavengerHuntStateKey, newScavengerHuntState)
                        active = false
                    }}>
                    <StickyNoteButton {newScavengerHuntState} />
                </form>
            {:else}
                <form
                    on:submit={() => {
                        $scavengerHuntState = newScavengerHuntState
                        active = false
                    }}>
                    <HiddenInputs excludeStates={[scavengerHuntStateKey]} />
                    <StickyNoteButton {newScavengerHuntState} />
                </form>
            {/if}
        {/if}
    </div>
{/if}

<style>
    .sticky-note {
        aspect-ratio: 1/1;
        padding: 1em;
        place-content: center;
        inset: 0;
        font-size: var(--static-scale-100);
    }
    :global(.sticky-note > *:not(picture)) {
        z-index: 1337;
    }
    :global(.sticky-note picture:nth-of-type(1)) {
        inset: 0;
    }
    :global(.sticky-note picture:nth-of-type(2)) {
        pointer-events: none;
        z-index: 10;
        top: 0;
        translate: 0 -50%;
    }
    :global(.sticky-note picture:nth-of-type(2) img) {
        height: 25px;
        rotate: var(--rotation-amount);
    }
    :global(.sticky-note picture) {
        position: absolute;
    }
    :global(.sticky-note button),
    :global(.sticky-note img) {
        height: 100%;
        border-radius: 3px;
    }
    :global(.sticky-note p),
    :global(.sticky-note button) {
        color: var(--black);
    }
    :global(.sticky-note button),
    :global(.sticky-note p) {
        font-family: var(--font-family-accent) !important;
    }
    .sticky-note form,
    .sticky-note :global(button) {
        position: absolute;
        height: 100%;
        width: 100%;
    }
    :global(.sticky-note button) {
        color: var(--white);
        border: none !important;
        background-color: var(--black-90-percent);
        opacity: 0;
        text-decoration: underline;
        transition: opacity 420ms ease-in-out;
        max-width: 100%;
    }
    :global([data-dark-mode="false"] .sticky-note button) {
        color: var(--black);
    }
    :global(.sticky-note:hover button),
    :global(.sticky-note button:focus) {
        opacity: 1;
    }
</style>
