<script lang="ts">
    import noteAvifSrcSet from "$assets/images/note-texture.png?width=256;512;1024&format=avif&srcset&imageTools"
    import noteWebpSrcSet from "$assets/images/note-texture.png?width=256;512;1024&format=webp&srcset&imageTools"
    import noteFallback from "$assets/images/note-texture.png?width=256&url&imageTools"
    import tapeAvifSrcSet from "$assets/images/tape-texture.png?format=avif&srcset&imageTools"
    import tapeWebpSrcSet from "$assets/images/tape-texture.png?format=webp&srcset&imageTools"
    import tapeFallback from "$assets/images/tape-texture.png?url&imageTools"
</script>

<picture class="note-texture">
    <source type="image/avif" srcset={noteAvifSrcSet} />
    <source type="image/webp" srcset={noteWebpSrcSet} />
    <img src={noteFallback} alt="sticky note texture generated by Dalle-2" />
</picture>
<picture class="tape-texture">
    <source type="image/avif" srcset={tapeAvifSrcSet} />
    <source type="image/webp" srcset={tapeWebpSrcSet} />
    <img src={tapeFallback} alt="tape texture generated by Dalle-2" />
</picture>

<style>
    .note-texture {
        inset: 0;
    }
    .tape-texture {
        pointer-events: none;
        z-index: 10;
        top: 0;
        translate: 0 -50%;
    }
    .tape-texture img {
        height: 25px;
        rotate: var(--rotation-amount);
    }
</style>
